### PR TITLE
Close dialog for editing node in Provenance graph after click on…

### LINKED ISSUE #154: Button in dialog for creating notes for a Provenance graph node does not work
* Release number or git hash: d6d337d70d9a454f1ca9794ff1cc4ae88fd9ac29
* Web browser version and OS: Chrome 78
* Environment (local or deployed): both

### Steps to reproduce

1. Open https://ordino.caleydoapp.org/
2. Select a dataset and make some changes
3. Select any node in the provenance graph and add notes (edit-icon on the right)
image
4. Write notes in the provided text field
image

### Observed behavior
* The extraction of the tags works
image

* Clicking the `OK` button has no effect; it does not close the dialog
* The notes are nevertheless saved in the dialog and reappear when the provenance graph node is edited again

### Expected behavior
* Clicking the `OK` button closes the dialog and saves the necessary information (notes and tags) which can be used later on

### PR DESCRIPTION
**Pull request by dvvanessastoiber**
Fixes #154

### CODE REVIEW

File: src/provvis.ts [hunk 1]
```diff
@@ -358,13 +358,13 @@ class StateRepr {
     $body.select('textarea').on('input', function() {
       $body.select('input.readonly').property('value', extractTags(this.value).join(' '));
     });
-
-    dia.onHide(() => {
+    $(dia.footer).find('button.btn-primary').on('click', function () {
```
Comment (thinkh) [inline src/provvis.ts]:
```suggestion
    dia.footer.querySelector('button.btn-primary').addEventListener('click', function () {
```
I suggest to use the native JS API instead of using jQuery. Please test if this works as well.
